version: "3"
services:
  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: admin
  #     POSTGRES_DB: testDB
  #     POSTGRES_HOST_AUTH_METHOD: trust
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: postgres@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      # MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: ropa
    ports:
      - "3306:3306"
    volumes:
      - "mysqldata:/var/lib/mysql"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  app:
    container_name: server
    build: ./server
    # build:
    #   context: ./server
    #   dockerfile: dockerfile
    # image: backend-services
    restart: always
    ports:
      - "5555:5555"
    depends_on:
      - db

  # client:
  #   container_name: client-ropa
  #   build: ./client
  #   # build:
  #   #   context: ./client
  #   #   dockerfile: dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #     - app

volumes:
  mysqldata: 
  # postgres-data:
